[project]
name = "repl-nix-telegramminihello"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.11",
    "python-telegram-bot>=21.9",
]
